<?php
$cars = array (
  0 => 
  array (
    'id' => '1',
    'name' => 'Toyota Fortuner',
    'image' => 'toyota_fortuner.webp',
    'type' => 'Внедорожник',
    'year' => 2025,
    'transmission' => 'АКПП',
    'seats' => 7,
    'fuel' => 'Дизель',
    'engine' => '2.8',
    'price' => 1500,
    'discount' => 10,
    'deposit' => 5000,
  ),
  1 => 
  array (
    'id' => '2',
    'name' => 'Honda Civic Hybrid',
    'image' => 'honda_civic.webp',
    'type' => 'Седан',
    'year' => 2023,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Гибрид',
    'engine' => '2.0',
    'price' => 1200,
    'deposit' => 5000,
  ),
  2 => 
  array (
    'id' => '3',
    'name' => 'Toyota Yaris Ativ',
    'image' => 'toyota_yaris_ativ.webp',
    'type' => 'Седан',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Бензин',
    'engine' => '1.2',
    'price' => 800,
    'deposit' => 5000,
  ),
  3 => 
  array (
    'id' => '4',
    'name' => 'Toyota Yaris Cross',
    'image' => 'toyota_yaris_cross.webp',
    'type' => 'Кроссовер',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Электро',
    'engine' => '1.5',
    'price' => 1100,
    'deposit' => 5000,
  ),
  4 => 
  array (
    'id' => '5',
    'name' => 'Honda Jazz',
    'image' => 'honda_jazz.webp',
    'type' => 'Хэтчбек',
    'year' => 2022,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Бензин',
    'engine' => '1.5',
    'price' => 700,
    'deposit' => 5000,
  ),
  5 => 
  array (
    'id' => '6',
    'name' => 'Hyundai H1',
    'image' => 'hyundai_h1.webp',
    'type' => 'Минивэн',
    'year' => 2023,
    'transmission' => 'АКПП',
    'seats' => 11,
    'fuel' => 'Дизель',
    'engine' => '2.5',
    'price' => 2500,
    'deposit' => 5000,
  ),
  6 => 
  array (
    'id' => '7',
    'name' => 'MG 5',
    'image' => 'mg_5.webp',
    'type' => 'Седан',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Бензин',
    'engine' => '1.5',
    'price' => 850,
    'deposit' => 5000,
  ),
  7 => 
  array (
    'id' => '8',
    'name' => 'MG ZS',
    'image' => 'mg_zs.webp',
    'type' => 'Кроссовер',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 5,
    'fuel' => 'Бензин',
    'engine' => '1.5',
    'price' => 950,
    'discount' => 15,
    'deposit' => 5000,
  ),
  8 => 
  array (
    'id' => '9',
    'name' => 'Toyota Veloz',
    'image' => 'toyota_veloz.webp',
    'type' => 'Минивэн',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 7,
    'fuel' => 'Бензин',
    'engine' => '1.5',
    'price' => 1300,
    'deposit' => 5000,
  ),
  9 => 
  array (
    'id' => '10',
    'name' => 'Ford Ranger',
    'image' => 'ford_ranger.webp',
    'type' => 'Пикап',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 4,
    'fuel' => 'Дизель',
    'engine' => '2.0',
    'price' => 1400,
    'deposit' => 5000,
  ),
  10 => 
  array (
    'id' => '11',
    'name' => 'Chevrolet Captiva',
    'image' => 'chevrolet_captiva.webp',
    'type' => 'Кроссовер',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 7,
    'fuel' => 'Бензин',
    'engine' => '1.5',
    'price' => 1450,
    'deposit' => 5000,
  ),
  11 => 
  array (
    'id' => '12',
    'name' => 'Toyota Hilux',
    'image' => 'toyota_hilux.webp',
    'type' => 'Пикап',
    'year' => 2024,
    'transmission' => 'АКПП',
    'seats' => 2,
    'fuel' => 'Дизель',
    'engine' => '2.4',
    'price' => 1000,
    'discount' => 10,
    'discount_start' => '07.04.2026',
    'discount_end' => '24.04.2026',
    'deposit' => 5000,
    'status' => 'active',
  ),
);
